name: Move YH Club Website to Root

on:
  workflow_dispatch:

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: Young_hustlers_club

      - name: Move files to root
        run: |
          mv "YH Club Website"/* .
          rm -rf "YH Club Website"

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Move YH Club Website to root directory"
          git push
